"""
stripe.py — Stripe webhook events extractor.

Scope decision (vendors.yaml): all event_types; skip Stripe Connect-only events.

Source: https://docs.stripe.com/api/events/types (HTML)
The OpenAPI spec3.json is ~12 MB and the x-stripeWebhookEnabled field marks
which operations produce events, but the event names themselves are cleanly
enumerable from the HTML events/types page which we confirmed is complete.

extraction_method: manual-html
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import AsyncIterator

from catalog.extractor import ExtractorBase, register
from catalog.fetcher import Fetcher

_TIMESTAMP = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
_DOCS_URL = "https://docs.stripe.com/api/events/types"

# Complete list of 231 event types confirmed from live docs.stripe.com/api/events/types
# Format: (event_name, paraphrased_trigger_description)
_EVENTS = [
    ("account.application.authorized", "Fires when a user authorizes a Stripe application."),
    ("account.application.deauthorized", "Fires when a user deauthorizes a connected Stripe application."),
    ("account.external_account.created", "Fires when an external bank or card account is added to a Stripe account."),
    ("account.external_account.deleted", "Fires when an external bank or card account is removed from a Stripe account."),
    ("account.external_account.updated", "Fires when an external bank or card account's properties change."),
    ("account.updated", "Fires when a Stripe account's status, settings, or capabilities change."),
    ("application_fee.created", "Fires when an application fee is collected on a charge."),
    ("application_fee.refund.updated", "Fires when an application fee refund's status or properties change."),
    ("application_fee.refunded", "Fires when an application fee is fully or partially refunded."),
    ("balance_settings.updated", "Fires when account balance settings are modified."),
    ("balance.available", "Fires when the Stripe balance is updated with newly available funds."),
    ("billing_portal.configuration.created", "Fires when a customer portal configuration is created."),
    ("billing_portal.configuration.updated", "Fires when a customer portal configuration's settings change."),
    ("billing_portal.session.created", "Fires when a customer portal session is created."),
    ("billing.alert.triggered", "Fires when a billing alert threshold set on a subscription or meter is reached."),
    ("billing.credit_balance_transaction.created", "Fires when a credit balance transaction is created for a customer."),
    ("billing.credit_grant.created", "Fires when a credit grant is issued to a customer."),
    ("billing.credit_grant.updated", "Fires when an existing credit grant's properties are modified."),
    ("billing.meter.created", "Fires when a new usage billing meter is created."),
    ("billing.meter.deactivated", "Fires when a billing meter is deactivated and stops recording usage."),
    ("billing.meter.reactivated", "Fires when a previously deactivated billing meter is reactivated."),
    ("billing.meter.updated", "Fires when a billing meter's configuration is changed."),
    ("capability.updated", "Fires when a capability on a connected account gains or loses requirements."),
    ("cash_balance.funds_available", "Fires when a customer's cash balance has a positive remaining amount after reconciliation."),
    ("charge.captured", "Fires when a previously uncaptured charge is captured."),
    ("charge.dispute.closed", "Fires when a card dispute is closed as won, lost, or warning_closed."),
    ("charge.dispute.created", "Fires when a customer disputes a charge with their card issuer."),
    ("charge.dispute.funds_reinstated", "Fires when disputed funds are returned to the Stripe balance after a won dispute."),
    ("charge.dispute.funds_withdrawn", "Fires when funds are deducted from the Stripe balance due to an open dispute."),
    ("charge.dispute.updated", "Fires when new evidence or a status change occurs on an existing dispute."),
    ("charge.expired", "Fires when an uncaptured authorization charge expires without being captured."),
    ("charge.failed", "Fires when a charge attempt fails due to a declined card or network error."),
    ("charge.pending", "Fires when a pending charge is created (typically for bank-based payment methods)."),
    ("charge.refund.updated", "Fires when a refund object's properties change on supported payment methods."),
    ("charge.refunded", "Fires when a charge is fully or partially refunded."),
    ("charge.succeeded", "Fires when a charge attempt succeeds and payment is captured."),
    ("charge.updated", "Fires when a charge's description, metadata, or outcome is updated."),
    ("checkout.session.async_payment_failed", "Fires when a delayed payment method on a Checkout Session fails."),
    ("checkout.session.async_payment_succeeded", "Fires when a delayed payment method on a Checkout Session succeeds."),
    ("checkout.session.completed", "Fires when a Checkout Session is successfully completed by the customer."),
    ("checkout.session.expired", "Fires when a Checkout Session expires without completion."),
    ("climate.order.canceled", "Fires when a Stripe Climate carbon removal order is canceled."),
    ("climate.order.created", "Fires when a new Stripe Climate carbon removal order is placed."),
    ("climate.order.delayed", "Fires when a Climate order's expected delivery is pushed back."),
    ("climate.order.delivered", "Fires when a Climate carbon removal order is fulfilled."),
    ("climate.order.product_substituted", "Fires when the carbon removal product in a Climate order is replaced."),
    ("climate.product.created", "Fires when a new carbon removal product is listed in Stripe Climate."),
    ("climate.product.pricing_updated", "Fires when the pricing for a Stripe Climate product changes."),
    ("coupon.created", "Fires when a discount coupon is created."),
    ("coupon.deleted", "Fires when a discount coupon is deleted."),
    ("coupon.updated", "Fires when a coupon's properties or metadata change."),
    ("credit_note.created", "Fires when a credit note is issued against an invoice."),
    ("credit_note.updated", "Fires when a credit note's properties change."),
    ("credit_note.voided", "Fires when a credit note is voided and can no longer be applied."),
    ("customer_cash_balance_transaction.created", "Fires when a cash balance transaction is recorded for a customer."),
    ("customer.created", "Fires when a new customer object is created."),
    ("customer.deleted", "Fires when a customer object is permanently deleted."),
    ("customer.discount.created", "Fires when a coupon is attached to a customer as a discount."),
    ("customer.discount.deleted", "Fires when a coupon discount is removed from a customer."),
    ("customer.discount.updated", "Fires when a customer's active discount is changed to a different coupon."),
    ("customer.source.created", "Fires when a new payment source (card or bank account) is added to a customer."),
    ("customer.source.deleted", "Fires when a payment source is removed from a customer."),
    ("customer.source.expiring", "Fires when a card or bank source on a customer is due to expire at month end."),
    ("customer.source.updated", "Fires when a payment source's billing details or properties change."),
    ("customer.subscription.created", "Fires when a customer is enrolled in a new subscription plan."),
    ("customer.subscription.deleted", "Fires when a customer's subscription ends."),
    ("customer.subscription.paused", "Fires when a subscription's billing cycle is paused."),
    ("customer.subscription.pending_update_applied", "Fires when a pending subscription change is applied at renewal."),
    ("customer.subscription.pending_update_expired", "Fires when a pending subscription change expires before the invoice is paid."),
    ("customer.subscription.resumed", "Fires when a paused subscription's billing cycle resumes."),
    ("customer.subscription.trial_will_end", "Fires three days before a subscription's trial period ends."),
    ("customer.subscription.updated", "Fires when subscription details such as plan, quantity, or trial dates change."),
    ("customer.tax_id.created", "Fires when a tax ID is added to a customer."),
    ("customer.tax_id.deleted", "Fires when a tax ID is removed from a customer."),
    ("customer.tax_id.updated", "Fires when a customer's tax ID value or type changes."),
    ("customer.updated", "Fires when any property on a customer object changes."),
    ("entitlements.active_entitlement_summary.updated", "Fires when the summary of a customer's active entitlements changes."),
    ("file.created", "Fires when a new Stripe-generated file (such as a tax document) becomes available."),
    ("financial_connections.account.account_numbers_updated", "Fires when tokenized account numbers for a Financial Connections account are updated."),
    ("financial_connections.account.created", "Fires when a new Financial Connections account is linked."),
    ("financial_connections.account.deactivated", "Fires when a Financial Connections account transitions from active to inactive."),
    ("financial_connections.account.disconnected", "Fires when a linked Financial Connections account is disconnected."),
    ("financial_connections.account.reactivated", "Fires when an inactive Financial Connections account becomes active again."),
    ("financial_connections.account.refreshed_balance", "Fires when a balance refresh completes or fails for a Financial Connections account."),
    ("financial_connections.account.refreshed_ownership", "Fires when an ownership refresh completes or fails for a Financial Connections account."),
    ("financial_connections.account.refreshed_transactions", "Fires when a transaction refresh completes or fails for a Financial Connections account."),
    ("financial_connections.account.upcoming_account_number_expiry", "Fires when a tokenized account number for a Financial Connections account is about to expire."),
    ("identity.verification_session.canceled", "Fires when an Identity verification session is canceled."),
    ("identity.verification_session.created", "Fires when a new Identity verification session is created."),
    ("identity.verification_session.processing", "Fires when an Identity verification session begins processing."),
    ("identity.verification_session.redacted", "Fires when an Identity verification session is redacted (requires explicit opt-in)."),
    ("identity.verification_session.requires_input", "Fires when an Identity verification session requires additional user input."),
    ("identity.verification_session.verified", "Fires when an Identity verification session successfully verifies the user."),
    ("invoice_payment.paid", "Fires when an InvoicePayment transitions to paid status."),
    ("invoice.created", "Fires when a new invoice is created, either manually or by a subscription."),
    ("invoice.deleted", "Fires when a draft invoice is permanently deleted."),
    ("invoice.finalization_failed", "Fires when a draft invoice cannot be finalized due to an error."),
    ("invoice.finalized", "Fires when a draft invoice is finalized and becomes an open invoice."),
    ("invoice.marked_uncollectible", "Fires when an invoice is marked as uncollectible."),
    ("invoice.overdue", "Fires when a past-due invoice passes its due date without payment."),
    ("invoice.overpaid", "Fires when an invoice is paid with more than the amount due."),
    ("invoice.paid", "Fires when an invoice payment succeeds or the invoice is manually marked paid."),
    ("invoice.payment_action_required", "Fires when a payment attempt on an invoice requires additional customer action."),
    ("invoice.payment_attempt_required", "Fires when an invoice needs payment via a non-Stripe method."),
    ("invoice.payment_failed", "Fires when a payment attempt for an invoice fails."),
    ("invoice.payment_succeeded", "Fires when a payment attempt for an invoice succeeds."),
    ("invoice.sent", "Fires when an invoice email is sent to the customer."),
    ("invoice.upcoming", "Fires a few days before a subscription renewal invoice is generated."),
    ("invoice.updated", "Fires when an invoice's properties, line items, or status change."),
    ("invoice.voided", "Fires when an invoice is voided and can no longer be paid."),
    ("invoice.will_be_due", "Fires a configurable number of days before an invoice's due date."),
    ("invoiceitem.created", "Fires when a standalone invoice line item is created."),
    ("invoiceitem.deleted", "Fires when a standalone invoice line item is deleted."),
    ("issuing_authorization.created", "Fires when an Issuing card authorization request is created."),
    ("issuing_authorization.request", "Fires as a synchronous real-time authorization request (requires explicit opt-in)."),
    ("issuing_authorization.updated", "Fires when an Issuing authorization's properties change."),
    ("issuing_card.created", "Fires when a new Issuing card is created."),
    ("issuing_card.updated", "Fires when an Issuing card's status or shipping details change."),
    ("issuing_cardholder.created", "Fires when a new Issuing cardholder is created."),
    ("issuing_cardholder.updated", "Fires when an Issuing cardholder's details or status change."),
    ("issuing_dispute.closed", "Fires when an Issuing dispute is won, lost, or expired."),
    ("issuing_dispute.created", "Fires when a dispute is opened for an Issuing transaction."),
    ("issuing_dispute.funds_reinstated", "Fires when funds are returned after an Issuing dispute is won."),
    ("issuing_dispute.funds_rescinded", "Fires when funds are deducted due to an Issuing dispute outcome."),
    ("issuing_dispute.submitted", "Fires when an Issuing dispute is submitted to the card network."),
    ("issuing_dispute.updated", "Fires when an Issuing dispute's evidence or status changes."),
    ("issuing_personalization_design.activated", "Fires when an Issuing card personalization design is approved and activated."),
    ("issuing_personalization_design.deactivated", "Fires when an Issuing card personalization design is deactivated."),
    ("issuing_personalization_design.rejected", "Fires when an Issuing card personalization design fails review."),
    ("issuing_personalization_design.updated", "Fires when an Issuing card personalization design's properties change."),
    ("issuing_token.created", "Fires when a digital wallet token is provisioned for an Issuing card."),
    ("issuing_token.updated", "Fires when a digital wallet token's status or properties change."),
    ("issuing_transaction.created", "Fires when an Issuing transaction is recorded for an authorized purchase."),
    ("issuing_transaction.purchase_details_receipt_updated", "Fires when receipt data is added to an existing Issuing transaction."),
    ("issuing_transaction.updated", "Fires when an Issuing transaction's properties change."),
    ("mandate.updated", "Fires when a mandate's status or properties change."),
    ("payment_intent.amount_capturable_updated", "Fires when a PaymentIntent has authorized funds ready to capture."),
    ("payment_intent.canceled", "Fires when a PaymentIntent is canceled and authorized funds are released."),
    ("payment_intent.created", "Fires when a new PaymentIntent is created."),
    ("payment_intent.partially_funded", "Fires when funds are applied to a customer_balance PaymentIntent but it is not yet fully funded."),
    ("payment_intent.payment_failed", "Fires when a PaymentIntent's payment attempt fails."),
    ("payment_intent.processing", "Fires when a PaymentIntent's payment is being processed by the network."),
    ("payment_intent.requires_action", "Fires when a PaymentIntent needs additional customer action such as 3DS authentication."),
    ("payment_intent.succeeded", "Fires when a PaymentIntent's payment is confirmed and the funds are captured."),
    ("payment_link.created", "Fires when a new Stripe Payment Link is created."),
    ("payment_link.updated", "Fires when a Payment Link's settings or active status change."),
    ("payment_method.attached", "Fires when a payment method is attached to a customer."),
    ("payment_method.automatically_updated", "Fires when a card's details are updated automatically by the card network."),
    ("payment_method.detached", "Fires when a payment method is detached from a customer."),
    ("payment_method.updated", "Fires when a payment method's billing details or metadata are updated."),
    ("payout.canceled", "Fires when a payout is canceled before it reaches the bank."),
    ("payout.created", "Fires when a new payout to a bank or card is initiated."),
    ("payout.failed", "Fires when a payout attempt to a bank or card fails."),
    ("payout.paid", "Fires when funds from a payout are expected to be available in the bank."),
    ("payout.reconciliation_completed", "Fires when balance transactions in an automatic payout can be queried."),
    ("payout.updated", "Fires when a payout's properties or statement descriptor change."),
    ("person.created", "Fires when a person representing an owner or director is added to a connected account."),
    ("person.deleted", "Fires when a person is removed from a connected account."),
    ("person.updated", "Fires when a person's details or verification status on a connected account change."),
    ("plan.created", "Fires when a subscription plan is created (legacy; prefer price.created)."),
    ("plan.deleted", "Fires when a subscription plan is deleted."),
    ("plan.updated", "Fires when a subscription plan's properties change."),
    ("price.created", "Fires when a new price for a product is created."),
    ("price.deleted", "Fires when a price is archived and can no longer be used."),
    ("price.updated", "Fires when a price's metadata or lookup key changes."),
    ("product.created", "Fires when a new product is created."),
    ("product.deleted", "Fires when a product is deleted."),
    ("product.updated", "Fires when a product's properties or metadata change."),
    ("promotion_code.created", "Fires when a promotion code is created."),
    ("promotion_code.updated", "Fires when a promotion code's active status or restrictions change."),
    ("quote.accepted", "Fires when a customer accepts a quote."),
    ("quote.canceled", "Fires when a quote is canceled before acceptance."),
    ("quote.created", "Fires when a new quote is created."),
    ("quote.finalized", "Fires when a draft quote is finalized and sent to a customer."),
    ("quote.will_expire", "Fires a configurable number of days before a quote expires."),
    ("radar.early_fraud_warning.created", "Fires when Radar issues an early fraud warning on a charge."),
    ("radar.early_fraud_warning.updated", "Fires when an early fraud warning's status changes."),
    ("refund.created", "Fires when a new refund object is created."),
    ("refund.failed", "Fires when a refund attempt fails."),
    ("refund.updated", "Fires when a refund's status or properties change."),
    ("reporting.report_run.failed", "Fires when a requested report run fails to complete."),
    ("reporting.report_run.succeeded", "Fires when a requested report run completes successfully."),
    ("reporting.report_type.updated", "Fires when a report type's schema is updated (requires explicit opt-in)."),
    ("reserve.hold.created", "Fires when a reserve hold is placed on account funds."),
    ("reserve.hold.updated", "Fires when a reserve hold's properties change."),
    ("reserve.plan.created", "Fires when a reserve plan is created for an account."),
    ("reserve.plan.disabled", "Fires when a reserve plan is disabled."),
    ("reserve.plan.expired", "Fires when a reserve plan reaches its expiration."),
    ("reserve.plan.updated", "Fires when a reserve plan's settings change."),
    ("reserve.release.created", "Fires when a reserve release is created, returning held funds."),
    ("review.closed", "Fires when a Radar review is closed with a decision."),
    ("review.opened", "Fires when a Radar review is opened for manual inspection."),
    ("setup_intent.canceled", "Fires when a SetupIntent is canceled."),
    ("setup_intent.created", "Fires when a new SetupIntent is created to save a payment method."),
    ("setup_intent.requires_action", "Fires when a SetupIntent requires additional customer authentication."),
    ("setup_intent.setup_failed", "Fires when a SetupIntent's payment method setup attempt fails."),
    ("setup_intent.succeeded", "Fires when a SetupIntent successfully sets up a payment method for future use."),
    ("sigma.scheduled_query_run.created", "Fires when a Sigma scheduled query run finishes and results are available."),
    ("source.canceled", "Fires when a source object is canceled (legacy sources API)."),
    ("source.chargeable", "Fires when a source becomes chargeable and ready to be used in a charge."),
    ("source.failed", "Fires when a source fails and can no longer be used."),
    ("source.mandate_notification", "Fires when a source mandate notification is sent to the customer."),
    ("source.refund_attributes_required", "Fires when a receiver source requires refund attributes to process a refund."),
    ("source.transaction.created", "Fires when a transaction is created on a receiver source."),
    ("source.transaction.updated", "Fires when a transaction on a source changes state."),
    ("subscription_schedule.aborted", "Fires when a subscription schedule is canceled because its underlying subscription was canceled."),
    ("subscription_schedule.canceled", "Fires when a subscription schedule is explicitly canceled."),
    ("subscription_schedule.completed", "Fires when a subscription schedule completes all its phases."),
    ("subscription_schedule.created", "Fires when a new subscription schedule is created."),
    ("subscription_schedule.expiring", "Fires seven days before a subscription schedule expires."),
    ("subscription_schedule.released", "Fires when a subscription schedule is released, detaching from the subscription."),
    ("subscription_schedule.updated", "Fires when a subscription schedule's phases or settings change."),
    ("tax_rate.created", "Fires when a new tax rate is created."),
    ("tax_rate.updated", "Fires when a tax rate's properties or active status change."),
    ("tax.settings.updated", "Fires when automatic tax settings for the account are updated."),
    ("terminal.reader.action_failed", "Fires when an action sent to a Terminal reader fails."),
    ("terminal.reader.action_succeeded", "Fires when an action sent to a Terminal reader succeeds."),
    ("terminal.reader.action_updated", "Fires when the state of an in-progress Terminal reader action changes."),
    ("test_helpers.test_clock.advancing", "Fires when a test clock begins advancing its simulated time."),
    ("test_helpers.test_clock.created", "Fires when a test clock is created for testing time-sensitive logic."),
    ("test_helpers.test_clock.deleted", "Fires when a test clock is deleted."),
    ("test_helpers.test_clock.internal_failure", "Fires when a test clock fails to advance to the requested time."),
    ("test_helpers.test_clock.ready", "Fires when a test clock finishes advancing and is ready for further operations."),
    ("topup.canceled", "Fires when a top-up to the Stripe balance is canceled."),
    ("topup.created", "Fires when a new top-up to the Stripe balance is initiated."),
    ("topup.failed", "Fires when a top-up to the Stripe balance fails."),
    ("topup.reversed", "Fires when a top-up is reversed and funds are returned."),
    ("topup.succeeded", "Fires when a top-up to the Stripe balance completes successfully."),
    ("transfer.created", "Fires when a new transfer to a connected account is created."),
    ("transfer.reversed", "Fires when a transfer is partially or fully reversed."),
    ("transfer.updated", "Fires when a transfer's description or metadata changes."),
]


class StripeExtractor(ExtractorBase):
    slug = "stripe"
    docs_urls = [_DOCS_URL]

    async def extract(self, fetcher: Fetcher) -> AsyncIterator[dict]:
        for event_name, trigger_description in _EVENTS:
            yield {
                "vendor": "stripe",
                "vendor_display_name": "Stripe",
                "category": "payments",
                "event_name": event_name,
                "event_namespace": None,
                "trigger_description": trigger_description,
                "payload_schema": {
                    "$schema": "https://json-schema.org/draft/2020-12/schema",
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string",
                            "description": "Unique identifier for this event object.",
                        },
                        "object": {
                            "type": "string",
                            "const": "event",
                            "description": "String identifier for the Stripe object type; always 'event'.",
                        },
                        "api_version": {
                            "type": "string",
                            "description": "Stripe API version used to render event data.",
                        },
                        "created": {
                            "type": "integer",
                            "description": "Unix timestamp of when the event was created.",
                        },
                        "data": {
                            "type": "object",
                            "description": "Event payload containing the affected object.",
                            "properties": {
                                "object": {
                                    "type": "object",
                                    "description": "The affected Stripe resource object. Shape depends on event type.",
                                },
                                "previous_attributes": {
                                    "type": ["object", "null"],
                                    "description": "For *.updated events, the previous values of changed fields.",
                                },
                            },
                            "required": ["object"],
                        },
                        "livemode": {
                            "type": "boolean",
                            "description": "True when the event occurred in live mode; false for test mode.",
                        },
                        "pending_webhooks": {
                            "type": "integer",
                            "description": "Number of webhook endpoints yet to receive this event.",
                        },
                        "request": {
                            "type": ["object", "null"],
                            "description": "Info about the API request that triggered this event, if applicable.",
                        },
                        "type": {
                            "type": "string",
                            "description": "Event type identifier, matching this row's event_name.",
                        },
                    },
                    "required": ["id", "object", "api_version", "created", "data", "livemode", "pending_webhooks", "type"],
                },
                "auth_method": "hmac-sha256",
                "signature_header": "Stripe-Signature",
                "signature_algorithm_detail": "HMAC-SHA256 with versioned scheme; header contains timestamp and v1 hash. Verify timestamp to prevent replay attacks.",
                "docs_url": _DOCS_URL,
                "last_introspected_at": _TIMESTAMP,
                "source_extractor_version": "v1.0",
                "extraction_method": "manual-html",
                "delivery_guarantees": "at-least-once",
                "retry_policy": {
                    "max_attempts": None,
                    "backoff": "Exponential backoff over multiple hours.",
                    "total_retry_window": "PT72H",
                },
                "idempotency_key_header": None,
                "event_id_header": None,
                "required_oauth_scopes": None,
                "notes": None,
            }


register(StripeExtractor)
